title: "Методы оптимизации. МФТИ 2023 - 2024"
baseurl: ""
url: "https://mipt23.fmin.xyz"
logo: "/images/logo.svg"
search_enabled: false

permalink: pretty

# For copy button on code
enable_copy_code_button: true

# Enable or disable heading anchors
heading_anchors: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true# Enable or disable heading anchors
heading_anchors: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Редактировать эту страницу на GitHub"
gh_edit_repository: "https://github.com/MerkulovDaniil/mipt23" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Aux links for the upper right navigation
aux_links:
  "💎 fmin.xyz":
    - "https://fmin.xyz"
  # "📜 Ведомость":
  #   - "https://docs.google.com/spreadsheets/d/1WNbD8Fij7xkGmXXqDa13DhZ7IIIQb2MesgAIHRjYe58/edit?usp=sharing"
  "📽 Videos":
    - "https://www.youtube.com/playlist?list=PLQSHEO58cjmMt8PY2H0ObJJ6FKbn0PoBx"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

math: katex

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false